authors:
  - Brandan Geise
classifiers:
  - "Template :: Site :: Credentials"
description: |
  This site template is used for Anti-Virus update pretexts and
  requests login info.
homepage: https://github.com/securestate/king-phisher
pages:
  - /login
  - /scan
title: Anti-Virus Update
version: 1.0
