authors:
  - Brandan Geise
classifiers:
  - "Template :: Site :: Credentials"
description: |
  This site template is used to represent an intranet login
  for gathering credentials.
homepage: https://github.com/securestate/king-phisher
pages:
  - /login
  - /login-verify
  - /forgot-password
title: Intranet Portal
version: 1.0
