authors:
  - Jeremy Schoeneman
classifiers:
  - "Template :: Site :: Credentials :: PDF"
description: |
  This site template is for a protected PDF document that
  requires users to login to view.
homepage: https://github.com/securestate/king-phisher
pages:
  - /file.html
  - /verify.html
title: PDF Harvester
version: 1.0
