authors:
  - Brandan Geise
classifiers:
  - "Template :: Site :: Credentials"
description: |
  This generic site template can be used with a range of pretexts 
  for gathering credentials.
homepage: https://github.com/securestate/king-phisher
pages:
  - /error
  - /register
title: Registration Sign Up
version: 1.0
