authors:
  - Brandan Geise
classifiers:
  - "Template :: Site :: Credentials"
description: |
  This site template can be used with any pretext to
  gather credentials.
homepage: https://github.com/securestate/king-phisher
pages:
  - /login
  - /error
title: Generic Portal
version: 1.0
